### ISSUE TITLE
Using Super key requires more than one press

### ISSUE THREAD

**Issue by mat-m** [rickyrockrat/parcellite#16] opened 2017-12-08 20:38 UTC
Hello I just installed parcellite 1.2.1 from the amd64 deb package on a fresh Mint 18.3. 

I have one issue because I use the super key (The Logo key) to have faster hotkeys: I use Super-V to get the history and select the entry I want. It is very near the Ctrl-V so it is easy to remember and natural to type.

But the history raises currently at the third press.
When the focus is in a text field (like here), and the mouse cursor is hovering the field, we see it change from I-beam to arrow on first press, back to I-beam on second press,  and history appaers on third press. 

Can  you reproduce ?

**Comment by rickyrockrat** [comment] 2017-12-16 05:05
My entry looks like 
<Super>V
And it actuates the first time every time. Check to see that something in your window manager doesn't also have it mapped.  I am running from Git, but there are very minor changes from 1.2.1 - and they are mostly cosmetic.

**Comment by mat-m** [comment] 2018-02-04 13:26
To define special keys, you have to type their code. If you just press the combination, you only get the character.

If I want to use `Alt-v`, I type  `<Meta>v` in the hotkey field. This one works on the first press.
If I want to use `Logo-v`, I type `<Super>v` in the hotkey field. On first press, I get a `v` typed, and on second press the menu triggers.
This does not occur with `Logo-E` under cinnamon which launches the files explorer (Nemo).
But pressing an unassigned combination leads to typed-in characters : <Super>c inserts a 'c' when the focus is in an input field.

I don't know the mechanism to trap hotkeys, but it looks like the first press is not trapped or trapped by someone else, then the second reaches Parcellite. 
Is there a way to debug this easily, as I am not a developer ?

**Comment by rickyrockrat** [comment] 2018-02-05 03:09
I am unable to duplicate here. My 'history key combination' is set to '<Super>v', and it works the first time every time. Go through all your key mappings for your WM, also see if you can find out anything via gsettings and org.cinnamon.muffin.keybindings

Another possibility is Ubuntu and Linux Mint stores xmodmap settings in /usr/share/X11/xkb/symbols/pc.

Also, if you exit parcellite, then launch it from the command line, look for key binding errors. If you get one, someone else has it bound.

**Comment by a4z** [comment] 2020-05-02 14:34
just searching for the same problem lead me here
I think it could be due to the desktop environment? 
with Mate, super key brings the (start) menu, so maybe therefore some people have this with the super key ....

**Comment by mat-m** [comment] 2020-06-30 21:21
Issue comes from Cinnamon. I can't reproduce with xfce

**Comment by manuman94** [comment] 2021-12-27 14:22
Yes! I'm having the same issue with Cinnamon.

**Comment by rickyrockrat** [comment] 2021-12-28 04:56
Have you launched parcellite from the command line and looked for key binding errors? I'm pretty sure the issue is that Cinnamon has that key bound already, but the command line errors should pin point it. You can't have two applications binding the same key.

**Comment by manuman94** [comment] 2021-12-28 09:18
Hi, I tried today. This is the result:

$ parcellite
Flag 0x0001, status 256, EXIT 1 STAT 1
Super+VFlag 0x0001, status 256, EXIT 1 STAT 1

Is this output normal?

Further, I tried looking for keyboard shorcuts using Super + V and I didn't find any. 

Thank you, greetings!

**Comment by rickyrockrat** [comment] 2021-12-30 05:05
Thank you for running that.
That's normal output and means you don't have Xdotool installed, or it's not in your path.
You should have gotten a "Binding 'xxxx' failed!" if your key was in use, which is not the case with you.

Here is the bug I bet you guys are hitting:
https://github.com/linuxmint/Cinnamon/issues/549
Gnome 3 strikes again: https://bugzilla.gnome.org/show_bug.cgi?id=662580
supposedly fixed in 3.8.
But it seems there are still issues with Cinnamon?
At any case, this does not look like a parcellite issue and I'm going to close it for now.

**Closed by rickyrockrat** 2021-12-30 05:05 UTC

**Comment by manuman94** [comment] 2021-12-30 08:19
Hi @rickyrockrat !

Yes, you're totally right.

By following https://github.com/linuxmint/cinnamon/issues/549#issuecomment-761878019 instructions I get the expected behaviour.

The only thing to care is that stop showing the start menu, but I never used <Super> key to open it. 

Thank you so much!
