### ISSUE TITLE
Lockup upon clear history while dialog is open

### ISSUE THREAD

**Issue by jubalh** [rickyrockrat/parcellite#95] opened 2024-07-11 08:21 UTC
* Click tray icon
* Select 'Clear history'
* Click tray icon (while the confirmation dialog is open)
 -> lockup

**Comment by rickyrockrat** [comment] 2024-10-27 17:11
This is a duplicate of #69. Basically, any dialog open and clicking the systray will lock the application.

**Closed by rickyrockrat** 2024-10-27 17:11 UTC
