### ISSUE TITLE
avoid trimming quotes

### ISSUE THREAD

**Issue by ggrrll** [rickyrockrat/parcellite#68] opened 2022-02-16 16:45 UTC
Hi, 

I do not understand why it's trimming the quotes while pasting 

thanks

ps: on L mint 20.3

**Comment by rickyrockrat** [comment] 2022-02-20 17:30
I need specific steps to get to the issue, what you expect and what you are getting. Also, be sure the trim options are as you expect in preferences. It is likely a setting, or if you are using xdotool (automatic paste) it may be an issue with the shell.

**Comment by ggrrll** [comment] 2022-02-21 10:52
Hi, 

I moved to CopyQ, which seems to no issues (until now), but for the sake of debugging, I can tell you that these were my settings

![image](https://user-images.githubusercontent.com/15370425/154940731-aefd5a15-16e6-40ee-9a25-372161186b17.png)


and that the issue happens when pressing enter on an item in the history   (pasting with `ctrl + V` is fine )

**Comment by c88tm** [comment] 2022-11-16 03:39
I ran into this issue too, it's a problem caused by the unescaped xdotool call.
If you copied just a single quote mark, you will get this log:
```
xdotool:'/bin/sh -c 'xdotool type "'"''
text:'''
```
which is worse than trimming, the app just crashes with segmentation fault.

But if the copied string still makes a valid xdotool call, such as `aaa"bbb"`, as the quotes canceled each other out, you'll get:
```
xdotool:'/bin/sh -c 'xdotool type "aaa"bbb""''
text:'aaa"bbb"'
``` 
And xdotool get rid of the quotes when parsing the string, resulting a trimming behavior.

**Comment by rickyrockrat** [comment] 2024-01-21 22:51
Duplicate of #87

**Closed by rickyrockrat** 2024-01-21 22:51 UTC
